# Generated by Django 4.2.6 on 2023-11-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('kundennummer', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('vorname', models.CharField(max_length=200)),
                ('strasse', models.CharField(max_length=200)),
                ('hausnummer', models.IntegerField()),
                ('plz', models.IntegerField()),
            ],
        ),
    ]
