# Generated by Django 4.2.6 on 2023-11-03 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("provider_portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contracts",
            fields=[
                (
                    "contract_id",
                    models.IntegerField(
                        max_length=10, primary_key=True, serialize=False
                    ),
                ),
                ("price_per_month", models.IntegerField()),
                ("description", models.CharField(max_length=200)),
                ("minimum_term", models.IntegerField(default=12)),
                ("notice_period", models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customer_id",
                    models.IntegerField(
                        max_length=10, primary_key=True, serialize=False
                    ),
                ),
                ("last_name", models.CharField(max_length=200)),
                ("first_name", models.CharField(max_length=200)),
                ("addresss", models.CharField(max_length=200)),
                ("house_number", models.IntegerField()),
                ("post_code", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Measurements",
            fields=[
                (
                    "measurement_id",
                    models.IntegerField(
                        max_length=10, primary_key=True, serialize=False
                    ),
                ),
                ("value", models.IntegerField()),
                ("timestamp", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Smartmeter",
            fields=[
                (
                    "smartmeter_id",
                    models.IntegerField(
                        max_length=10, primary_key=True, serialize=False
                    ),
                ),
                ("contract_start", models.DateField()),
                ("address", models.CharField(max_length=200)),
                ("house_numnber", models.IntegerField()),
                ("post_code", models.IntegerField()),
                (
                    "contract_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="provider_portal.contracts",
                    ),
                ),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="provider_portal.customer",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Kunde",
        ),
        migrations.AddField(
            model_name="measurements",
            name="smartmeter_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="provider_portal.smartmeter",
            ),
        ),
    ]
