# Generated by Django 4.2.6 on 2023-11-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("provider_portal", "0002_contracts_customer_measurements_smartmeter_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="smartmeter",
            old_name="contract_id",
            new_name="contract",
        ),
        migrations.RenameField(
            model_name="smartmeter",
            old_name="customer_id",
            new_name="customer",
        ),
    ]
