# Generated by Django 4.2.6 on 2023-11-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("provider_portal", "0005_delete_customers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=200)),
                ("first_name", models.CharField(max_length=200)),
                ("addresss", models.CharField(max_length=200)),
                ("house_number", models.IntegerField()),
                ("post_code", models.IntegerField()),
            ],
        ),
    ]
