# Generated by Django 4.2.6 on 2023-11-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("provider_portal", "0006_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customers",
        ),
    ]
