# Generated by Django 4.2.6 on 2023-11-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("provider_portal", "0007_delete_customers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "customer_id",
                    models.AutoField(max_length=10, primary_key=True, serialize=False),
                ),
                ("last_name", models.CharField(max_length=200)),
                ("first_name", models.CharField(max_length=200)),
                ("addresss", models.CharField(max_length=200)),
                ("house_number", models.IntegerField()),
                ("post_code", models.IntegerField()),
            ],
        ),
    ]
