# Generated by Django 4.2.6 on 2023-11-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("provider_portal", "0009_contracts_smartmeter_measurements"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customers",
            old_name="addresss",
            new_name="adress",
        ),
    ]
