version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - my_network

  database:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "3306:3306"
    networks:
      - my_network

networks:
  my_network:
